services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata_api
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - DB_PATH=${DB_PATH}
      - FLASK_APP=app.py
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: metadata_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

