version: '3.8'

services:
  app:
    build: .
    container_name: metadata_api
    ports:
      - "5000:5000"
    # environment:
    #   - FLASK_APP=wsgi.py
    #   - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: metadata_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

